set ffs=unix
set encoding=utf-8
set fileencoding=utf-8

" Fix color vim
if (has("nvim"))
  "For Neovim 0.1.3 and 0.1.4 < https://github.com/neovim/neovim/pull/2198 >
  let $NVIM_TUI_ENABLE_TRUE_COLOR=1
endif

"For Neovim > 0.1.5 and Vim > patch 7.4.1799 < https://github.com/vim/vim/commit/61be73bb0f965a895bfb064ea3e55476ac175162 >
"Based on Vim patch 7.4.1770 (`guicolors` option) < https://github.com/vim/vim/commit/8a633e3427b47286869aa4b96f2bfc1fe65b25cd >
" < https://github.com/neovim/neovim/wiki/Following-HEAD#20160511 >
if (has("termguicolors"))
  set termguicolors
endif

" Plugins
call plug#begin('~/.local/share/nvim/plugged')
"
Plug 'plasticboy/vim-markdown'
Plug 'scrooloose/nerdtree'
Plug 'ctrlpvim/ctrlp.vim'
Plug 'jremmen/vim-ripgrep'
Plug 'tpope/vim-surround'
Plug 'mhinz/vim-signify'
Plug 'editorconfig/editorconfig-vim'
Plug 'majutsushi/tagbar'
Plug 'terryma/vim-multiple-cursors'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'leafgarland/typescript-vim'
Plug 'drewtempelmeyer/palenight.vim'

call plug#end()

" Nert tree
map <c-t> :NERDTreeToggle<cr>

" Tabs manage
nnoremap <silent> <tab> :bn<CR>
nnoremap <silent> <S-tab> :bp<CR>
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#formatter = 'unique_tail'

" Ctrl p
let g:ctrlp_custom_ignore = '\v[\/](\.(git|hg|svn)|tags|vendor|public|storage)$'

" Convenient
set number
set mouse=a

" Tag
nmap <F8> :TagbarToggle<CR>
function UpdateTags()
	!eval 'ctags -R -o newtags; mv newtags tags' &
endfunction
nmap <silent> <F4> <Esc>:call UpdateTags()<CR>

" Colorshemes

" Whitespace
let g:HLSpace = 1
set listchars=tab:>·,trail:~,extends:>,precedes:<,space:␣,eol:¬,nbsp:·
set showbreak=↪\ 

function ToggleSpaceUnderscoring()
	if g:HLSpace
		set list
	else
		set nolist
	endif

	let g:HLSpace = !g:HLSpace
endfunction

nmap <silent> <F3> <Esc>:call ToggleSpaceUnderscoring()<CR>

let g:vim_markdown_folding_disabled = 1

let g:airline_theme = "palenight"

set background=dark
colorscheme palenight
